# ════════════════════════════════════════════════
# GOLAPP - Configuración de la Aplicación
# ════════════════════════════════════════════════

# ── Servidor ──
server.port=8089

# ── Datasource (PostgreSQL) ──
spring.datasource.url=jdbc:postgresql://localhost:5435/golapp_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ──
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ── Nombre de la aplicación ──
spring.application.name=golapp-backend

# ── JWT ──
jwt.secret=G0L4PP_S3CR3T_K3Y_TFG_2026_S3CUR1TY_T0K3N_V3RY_L0NG_K3Y_F0R_HS256
jwt.expiration=86400000

# ── Subida de archivos ──
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
app.upload.dir=uploads
